### ISSUE TITLE
node12 is depreciated => use node16 instead 

### ISSUE THREAD

**Issue by RobTillaart** [arduino/arduino-lint-action#182]
### Describe the problem

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

When linting a new library I got the following error message regarding the version of node.js to use

```
[lint](https://github.com/RobTillaart/PERIPUMP/actions/runs/3252047306/jobs/5345150366)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, arduino/arduino-lint-action, actions/checkout
```

See - https://github.com/RobTillaart/PERIPUMP/actions/runs/3252047306

I think this file might need an update
- https://github.com/arduino/arduino-lint-action/blob/main/action.yml

### To reproduce

See - https://github.com/RobTillaart/PERIPUMP/actions/runs/3252047306

### Expected behavior

that the error disappears?

### 'arduino/arduino-lint-action' version

arduino/arduino-lint-action@v1

### Additional context

https://github.com/RobTillaart/PERIPUMP/blob/master/.github/workflows/arduino-lint.yml

```yml
name: Arduino-lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-lint-action/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details
