### ISSUE TITLE
Update Node.js needed

### ISSUE THREAD

**Issue by RobTillaart** [arduino/arduino-lint-action#344]
### Describe the request

When running Arduino lint I get the message below:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, arduino/arduino-lint-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Describe the current behavior

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, arduino/arduino-lint-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### 'arduino/arduino-lint-action' version

arduino/arduino-lint-action@v4

### Additional context

See https://github.com/RobTillaart/MAX471_RT/actions/runs/7725600945/job/21060166703

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-lint-action/issues?q=)
- [X] I verified the feature was still missing when using the latest version
- [X] My request contains all necessary details

**Comment by clavisound** [comment]
Slint checking is failing.

`The following actions uses Node.js version which is deprecated and will be forced to run on node20: arduino/arduino-lint-action@v1.0.2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/`

**Comment by clavisound** [comment]
I don't know if it helps.

I changed from basic yml
```
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
```

to the 'complex' - I also added name - and it works.

```
name: arduino-lint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
```
